### ISSUE TITLE
The class 'org.omnifaces.component.input.Form' does not have the property 'value'

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#31]
I did a few more tests with respect to filtering and sorting after migrating to PrimeFaces 8 and using the latest snapshot.
The following exception occurs as soon as I call a backing from within a row when filtering is active.

# Exception
```
javax.el.PropertyNotFoundException: .../META-INF/resources/optimusfaces/tags/column.xhtml @59,3 filterValue="#{$pagedDataModel.filters[field]}": .../META-INF/resources/optimusfaces/tags/column.xhtml @28,61 value="#{$dataTable.value}": The class 'org.omnifaces.component.input.Form' does not have the property 'value'.
    at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:97)
    at org.primefaces.component.datatable.DataTable.processUpdates(DataTable.java:322)
    at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:952)
    at org.primefaces.component.outputpanel.OutputPanel.processUpdates(OutputPanel.java:98)
    at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:952)
    at javax.faces.component.UIForm.processUpdates(UIForm.java:262)
    at org.omnifaces.component.input.Form.processUpdates(Form.java:175)
    at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:952)
    at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:952)
    at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:952)
    at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:1368)
    at com.sun.faces.lifecycle.UpdateModelValuesPhase.execute(UpdateModelValuesPhase.java:54)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
    at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
    at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:133)
    at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:118)
    at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
    ...
```

**Comment by BalusC** [comment]
Fixed, thanks for the report!
